exports.al = {
  slug: "grades-12-13", label: "Grades 12 and 13 (A/L General English)", book: "Advanced Level General English textbook (one book for Grades 12 and 13)",
  note: "Grades 12 and 13 share one General English textbook with eight units, so there is no separate Grade 12 or Grade 13 book. These twenty plans (ten for each year) follow the eight units in order. Your school's scheme decides which units fall in Grade 12 and which in Grade 13. Stage times are for a 40-minute period.",
  plans: [
    [1, "Sri Lankan Achievers", "Reading 1 (an everyday hero)", "Reading for gist and detail",
      "identify the main idea of a story and explain why a person is admired.",
      "The Reading 1 text",
      ["Pairwork from the book: think of someone you admire and give two reasons.", "Pre-teach key words from the story."],
      ["Read for gist, then answer the detail questions."],
      ["Groups write a short profile of an everyday hero from their own village."],
      "Share one profile.", "Write a 150-word paragraph about someone you admire."],
    [1, "Sri Lankan Achievers", "Listening 1; Writing", "Listening for specific information",
      "note key facts from a talk and write a short profile of an achiever.",
      "The listening text (download from edupub.gov.lk), the achievers table",
      ["Discuss the famous Sri Lankans in Before Listening.", "Show how to take notes in a table."],
      ["Listen and complete the notes."],
      ["Complete the achievements table (Writing) and write a short profile of one achiever."],
      "Peer-check facts.", "Research another Sri Lankan achiever."],
    [2, "Living in Harmony", "Speaking and Writing", "Describing a picture and people",
      "describe a picture and a friend using appropriate adjectives.",
      "The Unit 2 picture",
      ["Describe the picture with the class: what are the children feeling?", "Show useful phrases: S/he likes ... S/he thinks ..."],
      ["Pairs describe the picture."],
      ["Write a short description of a friend using the sentence guide."],
      "Read two descriptions.", "Write about harmony in your school."],
    [2, "Living in Harmony", "Grammar: conditionals and modal verbs", "Conditionals and modals",
      "use conditional sentences and modal verbs to talk about coexistence.",
      "The harmony quotation",
      ["Read the quotation: If there is righteousness in the heart ...", "Show the first and second conditional forms."],
      ["Complete the grammar activities."],
      ["Groups write five rules for living in harmony using modals."],
      "Share the rules.", "Write a paragraph using three conditionals."],
    [3, "Relationships", "Speaking: quotations", "Discussing meaning",
      "discuss the meaning of quotations and give reasons.",
      "The quotations",
      ["Read the quotations.", "Show discussion phrases: I think it means ..."],
      ["Groups discuss the meanings."],
      ["Each group presents one interpretation."],
      "Class votes on the best interpretation.", "Write a quotation of your own and explain it."],
    [3, "Relationships", "Writing: a story", "Process writing",
      "write a story through prewriting, drafting, feedback and revising.",
      "The process-writing steps",
      ["Explain the steps in the book.", "Model prewriting with a mind map."],
      ["Pupils prewrite and draft."],
      ["Peer feedback and revision."],
      "Share one story.", "Finish the final draft."],
    [3, "Relationships", "Speaking: mini debates; Writing: essay", "Debating and a discursive essay",
      "take part in a mini debate and write a 250-word essay discussing both sides.",
      "The debate topics",
      ["Explain proposition and opposition.", "Show essay structure: introduction, both sides, conclusion."],
      ["Mini debates in groups."],
      ["Write a 250-word essay on one topic."],
      "Peer-check structure.", "Finish the essay."],
    [4, "English as a Local and Global Language", "Speaking and Writing 1", "Discussing advantages and difficulties",
      "list and explain the advantages and difficulties of learning English.",
      "The discussion questions",
      ["Discuss the two questions.", "Show how to support a point with an example."],
      ["Groups make a common list and select the six best points."],
      ["Write a paragraph with examples."],
      "Share one paragraph.", "Write about your own English learning."],
    [4, "English as a Local and Global Language", "Speaking 3; Language focus", "Describing feelings and hopes",
      "describe a picture and express feelings and hopes.",
      "The rural English class picture",
      ["Describe the picture.", "Show phrases: I hope ... I wish ..."],
      ["Pairwork: imagine being a student in the picture."],
      ["Write a short paragraph about hopes for learning English."],
      "Read one paragraph.", "Write about your ideal English class."],
    [4, "English as a Local and Global Language", "Grammar: future tenses", "Future forms",
      "use will, going to and the present continuous for the future.",
      "Future forms table",
      ["Show the three future forms.", "Contrast plans and predictions."],
      ["Complete the grammar activity."],
      ["Pairs talk about their plans after A/L."],
      "Share one plan.", "Write about your plans."],
    [5, "Crime and Social Responsibility", "Speaking 1; Reading 1", "Vocabulary of crime",
      "understand crime vocabulary and summarise news items.",
      "The dictionary definitions, the news items",
      ["Discuss the definitions of crime.", "Pre-teach vocabulary."],
      ["Read the six news items and answer the questions."],
      ["Summarise one news item for the class."],
      "Share summaries.", "Find a news item and summarise it."],
    [5, "Crime and Social Responsibility", "Reading 2", "Guessing meaning from context",
      "guess the meaning of words from context.",
      "Laws in different countries",
      ["Show strategies for guessing meaning.", "Read the first description together."],
      ["Read and guess the bold words."],
      ["Discuss which law is most surprising and why."],
      "Share views.", "Write about a law you would change."],
    [5, "Crime and Social Responsibility", "Grammar: direct and reported speech", "Reported speech",
      "change direct speech into reported speech.",
      "The monastery passage",
      ["Read the passage.", "Show the tense and pronoun changes."],
      ["Complete the grammar activity."],
      ["Report a conversation from the passage."],
      "Check tense changes.", "Report a conversation from home."],
    [6, "The Cyber World", "Reading 1; Writing emails", "Formal emails",
      "write a formal email with the correct structure and tone.",
      "The model emails",
      ["Discuss ways of keeping in touch.", "Show the structure of a formal email."],
      ["Analyse the model emails."],
      ["Write a formal email to a principal about a prefects' day (Writing task)."],
      "Peer-check tone.", "Finish the email."],
    [6, "The Cyber World", "Speaking: making a presentation", "Presentation skills",
      "plan and deliver a short presentation.",
      "The presentation guide",
      ["Read the guide on making a presentation.", "Show signposting phrases."],
      ["Groups plan a presentation."],
      ["Groups present."],
      "Feedback on delivery.", "Prepare a presentation outline."],
    [6, "The Cyber World", "Speaking: debate on social media", "Debating",
      "debate the advantages and disadvantages of social media.",
      "Debate topic",
      ["Explain debate rules.", "Brainstorm points."],
      ["Teams prepare arguments."],
      ["Hold the debate."],
      "Class decides the winning side.", "Write a paragraph on social media."],
    [7, "Continuing Education", "Speaking 1; Reading 1", "Discussing the future after school",
      "discuss feelings about leaving school and read about a technical college.",
      "The discussion questions, Maradana College of Technology text",
      ["Discuss the questions in pairs and groups.", "Look at the college picture."],
      ["Read the text and answer the questions."],
      ["Groups present options after A/L."],
      "Share one option.", "Write about your plans after school."],
    [7, "Continuing Education", "Speaking: table of diplomas; Listening", "Asking and answering questions from a table",
      "form questions from a table and listen for specific information.",
      "The diploma table, the listening text",
      ["Show question forms from the table.", "Pre-teach listening vocabulary."],
      ["Groups make ten questions from the table."],
      ["Listen to the conversation among four friends and answer."],
      "Share answers.", "Research one higher-education course."],
    [8, "Employment", "Reading: advertisements", "Reading job advertisements",
      "extract key information from job advertisements.",
      "The advertisements",
      ["Discuss where job advertisements appear.", "Pre-teach vocabulary."],
      ["Read the advertisements and answer the questions."],
      ["Choose a job and explain why it suits you."],
      "Share choices.", "Collect a real job advertisement."],
    [8, "Employment", "Writing: cover letter", "Writing a covering letter",
      "write a covering letter for a job advertisement.",
      "The model letters",
      ["Read the model letters.", "Show the structure of a covering letter."],
      ["Plan the letter."],
      ["Write a covering letter for one advertisement."],
      "Peer-check format.", "Finish the letter."]
  ]
};
