// Competencies and competency levels for Grades 6 to 11, taken from the NIE
// English Language Teachers' Guides for each grade. Each grade keeps its own
// guide's numbering and wording, because the guides do not always agree with
// each other (see the notes on Grades 7 and 11).
exports.NAMES = {
  1: "Identifies the sounds of English Language",
  2: "Uses mechanics of writing with understanding",
  3: "Engages in active listening and responds appropriately",
  4: "Builds up vocabulary using words appropriately and accurately to convey precise meaning",
  5: "Extracts necessary information from various types of texts",
  6: "Uses English grammar for the purpose of accurate and effective communication",
  7: "Uses English creatively and innovatively in written communication",
  8: "Communicates clearly, fluently and concisely"
};

const COMMON = {
  "1.1": "Pronounces English words properly",
  "1.2": "Reads aloud different types of texts accurately and meaningfully",
  "1.3": "Pronounces English words and phrases properly",
  "4.3": "Finds synonyms and antonyms for given words",
  "4.4": "Uses affixes to change the word class and the meaning of words",
  "4.5": "Forms the plurals of nouns",
  "5.2": "Extracts specific information from various types of simple texts",
  "5.3": "Transfers information into other forms",
  "5.4": "Reads and responds to simple poems",
  "5.6": "Extracts the general idea of a text",
  "6.1": "Constructs simple sentences",
  "6.2": "Uses pronouns appropriately",
  "6.3": "Uses modals meaningfully",
  "6.7": "Uses prepositions appropriately",
  "6.9": "Uses adverbs appropriately",
  "7.2": "Describes pictures",
  "7.3": "Writes for personal purposes",
  "7.4": "Writes instructions",
  "7.5": "Writes simple compositions on different types of topics",
  "7.6": "Writes poems and stories",
  "8.4": "Speaks on familiar topics",
  "8.9": "Describes pictures"
};
const pick = (nums, own) => nums.split(" ").map((n) => [n, own[n] || COMMON[n]]);

exports.GRADES = [
  {
    grade: "Grade 6",
    source: "Grade 6 Teachers' Guide (edition implemented from 2015). 47 competency levels.",
    note: "This is the Grade 6 syllabus that the 2014 to 2019 Pupil's Book follows. The new 2026 Grade 6 syllabus uses a different set of competencies; schools following it should use the new Teachers' Guide.",
    levels: pick("1.1 1.2 2.1 2.2 2.3 3.1 3.2 3.3 4.1 4.2 4.3 4.4 4.5 5.1 5.2 5.3 5.4 5.5 5.6 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.1 7.2 7.3 7.4 7.5 7.6 8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 8.10 8.11 8.12 8.13", {
      "2.1": "Uses capital and simple letters appropriately",
      "2.2": "Uses full stop appropriately",
      "2.3": "Uses question mark appropriately",
      "3.1": "Responds to simple announcements",
      "3.2": "Listens and follows instructions and responds to requests",
      "3.3": "Listens to a simple text for specific information",
      "4.1": "Uses masculine and feminine forms of nouns appropriately",
      "4.2": "Uses terms referring to young ones of animals appropriately",
      "5.1": "Uses visual clues to derive the meaning of the text",
      "5.5": "Reads and understands simple folk stories",
      "5.6": "Extracts the general idea of a text",
      "6.4": "Uses determiners",
      "6.5": "Uses contracted form",
      "6.6": "Uses adjectives",
      "6.8": "Uses conjunctions",
      "7.1": "Writes descriptions of people, animals, places and things",
      "8.1": "Introduces oneself to others",
      "8.2": "Uses simple expressions in greeting, thanking, affirming, denying",
      "8.3": "Describes objects, animals, people using simple sentence patterns",
      "8.5": "Describes things in the immediate surrounding using adjectives",
      "8.6": "Uses simple structures to show ability and possession",
      "8.7": "Asks and gets personal information from others",
      "8.8": "Describes the position of things",
      "8.10": "Speaks about daily actions",
      "8.11": "Describes past events and actions",
      "8.12": "Uses question words to get information",
      "8.13": "Uses language in variety of contexts"
    })
  },
  {
    grade: "Grade 7",
    source: "Grade 7 Teachers' Guide. The competency levels are listed as the guide presents them.",
    note: "The Grade 7 guide lists 8.18 with the same wording as 8.13. It is shown here as printed.",
    levels: pick("1.1 1.2 2.4 3.3 4.3 4.4 4.5 4.6 5.1 5.2 5.3 5.4 5.5 5.6 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.1 7.2 7.3 7.4 7.5 7.6 8.3 8.4 8.6 8.8 8.9 8.13 8.17 8.18", {
      "2.4": "Uses apostrophe appropriately",
      "3.3": "Listens and responds to different types of simple texts",
      "4.6": "Identifies collective nouns and compound nouns",
      "5.1": "Uses visual clues to derive the meaning of the text",
      "5.5": "Reads and understands simple folk stories",
      "6.4": "Uses determiners appropriately",
      "6.5": "Uses contracted form",
      "6.6": "Uses adjectives appropriately",
      "6.8": "Uses conjunctions appropriately",
      "7.1": "Writes descriptions of people, animals, places and things",
      "8.3": "Describes objects, animals, people using simple sentence patterns",
      "8.6": "Uses modals can, would, must and should",
      "8.8": "Describes the position of things",
      "8.13": "Uses language in variety of contexts",
      "8.17": "Describes continuing actions",
      "8.18": "Uses language in variety of contexts"
    })
  },
  {
    grade: "Grade 8",
    source: "Grade 8 Teachers' Guide. 36 competency levels.",
    levels: pick("1.1 1.2 2.5 3.2 3.3 3.4 4.3 4.4 4.5 4.7 5.1 5.2 5.3 5.4 5.5 5.6 6.1 6.2 6.3 6.5 6.6 6.7 6.8 6.9 7.1 7.2 7.3 7.4 7.5 7.6 8.3 8.4 8.6 8.8 8.9 8.13", {
      "2.5": "Uses inverted commas appropriately",
      "3.2": "Listens and follows instructions and responds to requests",
      "3.3": "Listens and responds to different types of simple texts",
      "3.4": "Listens and transfers information to other forms",
      "4.7": "Uses collective nouns and compound nouns",
      "5.1": "Uses visual and contextual clues to derive the meaning of the text",
      "5.5": "Reads and responds to simple folk stories / stories",
      "6.5": "Uses contracted forms",
      "6.6": "Uses adjectives appropriately",
      "6.8": "Uses conjunctions appropriately",
      "7.1": "Writes descriptions of things, places and people",
      "8.3": "Describes objects, animals, people using simple sentence patterns",
      "8.6": "Uses modals must, should, have to",
      "8.8": "Describes the position",
      "8.13": "Uses language in a variety of contexts"
    })
  },
  {
    grade: "Grade 9",
    source: "Grade 9 Teachers' Guide. 45 competency levels.",
    levels: pick("1.1 1.2 1.3 2.6 3.3 3.4 3.5 4.3 4.4 4.5 4.7 4.8 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.1 6.2 6.6 6.7 6.8 6.9 6.10 6.11 7.1 7.2 7.3 7.4 7.5 7.6 7.7 8.3 8.4 8.8 8.9 8.11 8.12 8.13 8.14 8.15", {
      "2.6": "Uses commas with understanding",
      "3.3": "Listens to a simple text for specific information",
      "3.4": "Listens and transfers information to other forms",
      "3.5": "Identifies different intonation patterns and uses of word stress",
      "4.7": "Uses nouns, verbs, adjectives and adverbs appropriately",
      "4.8": "Uses collective nouns and compound nouns properly",
      "5.1": "Uses visual clues to derive the meaning of texts",
      "5.5": "Reads and responds to simple folk tales",
      "5.7": "Infers ellipted information",
      "5.8": "Infers implied information",
      "5.9": "Recognizes the organization of a text",
      "6.6": "Uses adjectives properly",
      "6.8": "Uses conjunctions appropriately",
      "6.10": "Uses the conditional clauses appropriately",
      "6.11": "Uses reported speech accurately",
      "7.1": "Writes descriptions of people, animals, places and things",
      "7.7": "Writes for official purposes",
      "8.3": "Describes people, animals and objects using simple sentence patterns",
      "8.8": "Describes the position of things accurately",
      "8.11": "Describes past events and actions properly",
      "8.12": "Uses question words to get information",
      "8.13": "Uses language in a variety of contexts",
      "8.14": "Describes future events",
      "8.15": "Engages in telephone conversations"
    })
  },
  {
    grade: "Grade 10",
    source: "Grade 10 Teachers' Guide. 49 competency levels.",
    levels: pick("1.2 1.4 1.5 2.7 3.3 3.4 3.5 3.6 3.7 3.8 4.3 4.4 4.5 4.7 4.8 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.1 6.2 6.3 6.6 6.7 6.8 6.9 6.10 6.11 7.1 7.2 7.3 7.4 7.6 7.7 7.9 8.3 8.4 8.9 8.11 8.12 8.13 8.14 8.15 8.16", {
      "1.4": "Pronounces English words with different spellings",
      "1.5": "Pronounces English sentences properly",
      "2.7": "Uses exclamation mark appropriately",
      "3.3": "Listens to a simple text for specific information",
      "3.4": "Listens to and transfers information to other forms",
      "3.5": "Identifies different intonation patterns and uses of word stress",
      "3.6": "Listens to and reports information",
      "3.7": "Recognizes discourse markers",
      "3.8": "Takes notes from oral presentations",
      "4.7": "Uses nouns, verbs, adjectives and adverbs appropriately",
      "4.8": "Uses collective nouns and compound nouns",
      "5.1": "Uses visual and contextual clues to derive the meaning of the text",
      "5.5": "Reads and responds to simple folk stories",
      "5.7": "Infers ellipted information",
      "5.8": "Infers implied information",
      "5.9": "Recognizes the organization of a text",
      "6.6": "Uses adjectives appropriately",
      "6.8": "Uses conjunctions appropriately",
      "6.10": "Identifies 'If' type 3",
      "6.11": "Uses reported speech",
      "7.1": "Writes descriptions of people, animals, places and things",
      "7.7": "Writes for official purposes",
      "7.9": "Writes compositions",
      "8.3": "Describes objects, animals and people using simple sentence patterns",
      "8.11": "Describes past events and actions",
      "8.12": "Uses question words to get information",
      "8.13": "Uses language in a variety of contexts",
      "8.14": "Describes future events and actions",
      "8.15": "Engages in telephone conversations",
      "8.16": "Engages in debates"
    })
  },
  {
    grade: "Grade 11",
    source: "Grade 11 Teachers' Guide. The guide introduces no new competency levels for Grade 11: it brings together the levels of Grades 6 to 10 so that students can master them before the O/L examination.",
    note: "The Grade 11 guide numbers some levels differently from the Grade 10 guide (for example, Writes compositions is 7.9 in Grade 10 and 7.8 here; Engages in debates is 8.16 in Grade 10 and 8.18 here). The Grade 11 numbering is shown as printed.",
    levels: pick("1.1 1.2 1.3 1.4 2.1 2.2 2.3 2.4 2.5 2.6 2.7 3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 6.10 6.11 7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 8.10 8.11 8.12 8.13 8.14 8.15 8.16 8.17 8.18", {
      "1.4": "Pronounces English words with different spellings properly",
      "2.1": "Uses capital and simple letters appropriately",
      "2.2": "Uses full stop appropriately",
      "2.3": "Uses question mark appropriately",
      "2.4": "Uses apostrophes appropriately",
      "2.5": "Uses inverted commas appropriately",
      "2.6": "Uses commas with understanding",
      "2.7": "Uses exclamation mark appropriately",
      "3.1": "Responds to simple announcements",
      "3.2": "Listens and follows instructions",
      "3.3": "Listens and responds to different types of simple texts",
      "3.4": "Listens and transfers information to other forms",
      "3.5": "Identifies different intonation patterns and uses of word stress",
      "3.6": "Listens and reports information",
      "3.7": "Recognizes discourse markers",
      "3.8": "Takes notes from oral presentations",
      "4.1": "Uses masculine and feminine forms of nouns appropriately",
      "4.2": "Uses terms referring to young ones of animals appropriately",
      "4.6": "Identifies collective nouns and compound nouns",
      "4.7": "Uses nouns, verbs, adjectives and adverbs appropriately",
      "4.8": "Uses collective nouns and compound nouns properly",
      "5.1": "Uses visual clues to derive the meaning of texts",
      "5.5": "Reads and understands simple folk tales",
      "5.7": "Infers implied information",
      "5.8": "Recognizes the organization of a text",
      "6.4": "Uses determiners properly",
      "6.5": "Uses the contracted forms",
      "6.6": "Uses adjectives properly",
      "6.8": "Uses conjunctions appropriately",
      "6.10": "Uses the conditional clauses appropriately",
      "6.11": "Uses reported speech accurately",
      "7.1": "Writes descriptions of people, animals, places and things",
      "7.7": "Writes for official purposes",
      "7.8": "Writes compositions",
      "8.1": "Introduces self",
      "8.2": "Uses simple expressions appropriately in greeting, thanking, affirming, denying",
      "8.3": "Describes people, animals, and objects using simple sentence patterns",
      "8.5": "Describes things in the immediate surrounding using adjectives",
      "8.6": "Uses simple structures to show ability and possibility",
      "8.7": "Asks and gets personal information from others",
      "8.8": "Describes the position of things",
      "8.10": "Speaks about daily actions",
      "8.11": "Describes past events and actions properly",
      "8.12": "Uses question words to get information",
      "8.13": "Uses language in a variety of contexts",
      "8.14": "Describes continuing actions",
      "8.15": "Uses perfect tense appropriately",
      "8.16": "Describes future events and actions appropriately",
      "8.17": "Engages in telephone conversations",
      "8.18": "Engages in debates"
    })
  }
];
