// Plan fields: [unit, unitTitle, activity, focus, outcome, materials, presentation[], practice[], production[], close, homework]
exports.g3 = {
  slug: "grade-3", label: "Grade 3", book: "Grade 3 English Pupil's Book (new syllabus)",
  note: "Grade 3 is taught mainly through listening and speaking. Keep writing short and let pupils say everything before they write it. Stage times are for a 40-minute period; shorten them if your period is 30 minutes.",
  plans: [
    [1, "I, myself and me", "Say your name; Make your badge", "Greeting and saying your name",
      "greet a friend and say their own name using Hello! I'm ... and What's your name?",
      "Paper badges, crayons, a soft ball",
      ["Wave and say Hello! I'm Teacher. Repeat with two pupils.", "Hold up a name badge and model: What's your name? My name is ..."],
      ["Class repeats the two lines, then halves of the class say them to each other.", "Pass the ball: the pupil holding it answers What's your name? and asks the next pupil."],
      ["Pupils make and colour a name badge, then walk around and greet five friends using the badge."],
      "Sing a hello song together.", "Say Hello! I'm ... to three people at home."],
    [1, "I, myself and me", "Count, read and say; How old are you?", "Numbers one to ten and saying your age",
      "count from one to ten and say how old they are.",
      "Number cards 1 to 10, the picture page with the children's ages",
      ["Count ten pencils aloud, holding up a number card for each.", "Model: How old are you? I'm eight."],
      ["Pupils count in pairs, taking turns (Work in pairs. Take turns).", "Show a number card; pupils say the number and the word."],
      ["Pupils read the speech bubbles (Hi, I'm Kumar. I'm eight years old.) and then say the same about themselves to a partner."],
      "Count back from ten to one together.", "Count ten things at home and draw them."],
    [1, "I, myself and me", "Listen and say; Play the game", "Saying your grade and where you live",
      "say which grade they are in and where they live.",
      "A ball, a simple map of the area",
      ["Model: I'm in grade three. I live in Matara (use your own town).", "Ask two pupils What grade are you in? Where do you live?"],
      ["Chorus and pair repetition of the two questions and answers."],
      ["Play the ball game from the book: pupils in a circle pass the ball asking Where do you live? and answering I live in ..."],
      "Three pupils introduce themselves with name, age, grade and town.", "Draw your house and write I live in ... under it."],
    [2, "Home sweet home", "My family; Sing the song", "Family members",
      "name family members and introduce them with This is my ...",
      "Family picture from the book, word cards (mother, father, brother, sister)",
      ["Point to the family picture: This is my father. This is my mother.", "Stick the word cards next to each person."],
      ["Pupils point and say as the teacher names each member.", "Teach the Family Tree song line by line."],
      ["Pupils draw their own family and introduce it to a partner: This is my sister. She is a girl."],
      "Sing the song again with actions.", "Bring a family photo or drawing."],
    [3, "Our School", "Read aloud; Listen and match", "Places and people in the school",
      "name places in the school and match people with their jobs.",
      "Picture cards: library, office room, music room, playground, herbal garden; job cards",
      ["Walk the class to the door and point: This is the playground. That is the library.", "Show the job cards: Principal, Teacher, Librarian, Security guard."],
      ["Read aloud the place names from the book.", "Listen and match: the teacher describes a person and pupils point to the right card."],
      ["Pairs play I'm thinking of a place: one pupil mimes (reading, dancing) and the other names the place."],
      "Pupils name their favourite place in the school.", "Draw one place in the school and write its name."],
    [4, "My food bag", "Talk; Look and find; Listen and make a food bag", "Fruits and vegetables",
      "name common fruits and vegetables and say which ones they like.",
      "Real fruits and vegetables or pictures, a paper bag",
      ["Take fruits out of a bag one by one: This is a banana. This is a carrot.", "Model: I like mangoes."],
      ["Look and find: pupils point to each fruit in the book picture.", "Sort the picture cards into fruits and vegetables."],
      ["Listen and make a food bag: the teacher says four items and pupils draw them in a paper bag shape, then tell a partner what is in their bag."],
      "Class says which fruit most pupils like.", "Draw your favourite fruit and write I like ..."],
    [5, "Animal friends", "Look and say; Listen to the poem and recite", "Animals and their sounds and actions",
      "name animals, copy their actions and recite a short poem.",
      "Animal pictures or masks",
      ["Show animal pictures and name them. Make each animal's sound and action.", "Model: It is a cat. It says miaow."],
      ["Look and say, then Look and find in the book picture.", "Listen to the poem and recite it line by line."],
      ["Pupils make a simple mask (Make a mask) and act out the animal while the class guesses."],
      "Recite the poem with actions.", "Tell your family the name of three animals in English."],
    [6, "Clothes we wear", "Sing this song; Look, read and match", "Clothes and colours",
      "name clothes with their colours using has / I have.",
      "Real clothes (a hat, a belt, a scarf), colour cards",
      ["Put on a hat: I have a blue hat.", "Point to a pupil: Nimal has a white shirt."],
      ["Sing the song (Sonia has a blue hat...) and point to the clothes.", "Look, read and match the clothes words with the pictures."],
      ["Pupils describe what they are wearing to a partner: I have a white shirt and a blue short."],
      "Two pupils describe a friend while the class guesses who.", "Draw your favourite clothes and colour them."],
    [6, "Clothes we wear", "Time; Read the time", "Telling the time",
      "read and say o'clock, quarter past, half past and quarter to.",
      "A cardboard clock with moving hands",
      ["Move the clock hands: It is seven o'clock. It is half past seven.", "Show quarter past and quarter to."],
      ["Pupils read the times in the book.", "The teacher sets the clock; pupils say the time."],
      ["Pairs draw a clock face, set a time and ask What's the time?"],
      "Ask: What time do you come to school?", "Draw a clock showing the time you wake up."],
    [7, "Playing is fun", "Listen, repeat and act; Let's play a game", "Action words for games",
      "follow and give simple action instructions such as run, jump and kick.",
      "A ball, open space",
      ["Do the actions while saying them: Run! Jump! Kick the ball!", "Show Look! The ball rolls fast."],
      ["Listen, repeat and act: pupils copy the teacher.", "Simon says with the action words."],
      ["Small groups play a game while one leader gives the instructions in English."],
      "Pupils name the game they liked best.", "Teach one action game to a brother or sister."],
    [8, "The world around me", "Listen, point and repeat; Listen and read", "Things in a home garden",
      "name things in a garden and describe a tree using It has ...",
      "A picture of a garden, a real leaf and a small branch",
      ["Point to the garden picture: This is a tree. It has leaves. It has branches.", "Show the real leaf and branch."],
      ["Listen, point and repeat the garden words: bush, path, tree, pond, swing, fence.", "Read This is my garden. It has big trees."],
      ["Pupils draw their own garden or school garden and tell a partner three things it has."],
      "Say the Mother Nature lines together: Save water. Plant a tree.", "Water a plant at home and tell the class tomorrow."]
  ]
};

exports.g6 = {
  slug: "grade-6", label: "Grade 6", book: "Grade 6 English Pupil's Book (2014 to 2019 edition)",
  note: "These plans follow the Grade 6 Pupil's Book printed from 2014 to 2019. A new Grade 6 book was introduced in 2026 with different units; if your class uses it, treat these as model lessons and match them to your own book.",
  plans: [
    [1, "Hello", "Role play; Activity 7", "Introductions with am, is and are",
      "introduce themselves and a classmate and choose am, is or are correctly.",
      "The Unit 1 role play, a chart of am / is / are",
      ["Introduce yourself: I am Mrs Perera. I am your English teacher.", "Point to pupils: This is Nimal. He is in Grade 6. They are friends.", "Build the chart: I – am; he / she / it – is; we / you / they – are."],
      ["Read the role play in pairs.", "Chain drill: each pupil says I am ... and introduces the next pupil.", "Do Activity 7 (am, is or are) and check with a partner."],
      ["Groups of three write and act a short first-day meeting, using am, is and are at least five times."],
      "Two groups perform; the class listens for am, is and are.", "Write five sentences about your family using am, is and are."],
    [2, "Leisure Lesson", "Activities 5 and 6", "What people are doing now (present continuous)",
      "describe actions happening now with is / are + -ing.",
      "The Unit 2 picture, verb cards",
      ["Mime writing and ask What am I doing? Write You are writing.", "Show the pattern am / is / are + verb-ing and spelling changes (swim – swimming, make – making)."],
      ["Mime-and-guess with verb cards: She is swimming.", "Complete Activity 5."],
      ["Pairs describe the Unit 2 picture aloud, then write four sentences (Activity 6)."],
      "Check three -ing spellings on the board.", "Write what five family members are doing at 7 p.m. tonight."],
    [3, "Where's Everything?", "Activities 3, 4 and 6", "Prepositions of place",
      "say and write where things are with in, on, under, near, next to and between.",
      "A box, a pen, classroom objects",
      ["Use the box and pen: The pen is in / on / under the box.", "Place a book between two bags and write each preposition with a sketch."],
      ["Pair work: list classroom objects and say where they are (Activity 3).", "Write sentences about the picture (Activity 4)."],
      ["Listen and draw (Activity 6), then pupils describe their own picture for a partner to draw."],
      "Compare drawings: which pairs matched?", "Write five sentences about your bedroom."],
    [4, "What Can You See?", "Activities 1 and 2", "This, that, these, those",
      "use this / these for near things and that / those for things far away.",
      "Objects placed near and far from the teacher",
      ["Hold a pen: This is a pen. Point to one far away: That is a pen. Repeat with plurals.", "Draw a near / far, one / many table."],
      ["Complete Activity 1.", "Point-and-say game."],
      ["Activity 2: six sentences about things in and outside the classroom, using all four words."],
      "Read three sentences; the class points near or far.", "Label a drawing of your table with four sentences."],
    [5, "Aunt Minoli's Kitchen", "Activities 1 and 2", "Instructions in order",
      "give instructions for a simple recipe using imperatives and first, next, then, finally.",
      "Step pictures for making tea, sequence word cards",
      ["Act out making tea: First, boil the water. Next, put tea leaves in the pot.", "Point out that each instruction starts with a verb."],
      ["Match the soup steps with the pictures (Activity 1).", "Order the tea steps and add sequence words (Activity 2)."],
      ["Groups write steps for a simple snack; one pupil reads while another mimes."],
      "Did the mime follow the order?", "Write six steps for something you make at home."],
    [6, "What We Do", "Activities 4, 5 and 6", "Daily routines (present simple)",
      "ask and answer about routines and report them with the -s form.",
      "Find-someone-who cards",
      ["Tell your routine: I get up at 5 o'clock.", "Change it: She gets up at 5 o'clock. Underline the -s."],
      ["Drill Do you ...? Yes, I do. / No, I don't.", "Find someone who (Activity 4)."],
      ["Report to the class (Activity 5) and write the findings (Activity 6)."],
      "Correct He get up → He gets up.", "Write about a family member's day in six sentences."],
    [7, "A Fine Day", "Activities 3, 4 and 5", "Weather words and on / in / at",
      "name the weather and use on for days, in for months and at for times.",
      "A calendar, weather symbol cards",
      ["Show the calendar: My birthday is in June, on the 12th, at 4 o'clock.", "Build the rule table."],
      ["Listen and name the weather symbols (Activity 3).", "Complete the on / in / at sentences."],
      ["Pairs interview each other about birthdays and times and write three true sentences."],
      "Quick-fire: time word → preposition.", "Keep a weather diary for three days."],
    [8, "A Visit to the Zoo", "Activities 5, 6 and 7", "Ability with can and can't",
      "say what people and animals can and cannot do.",
      "Animal pictures, an ability chart",
      ["A fish can swim. A fish can't climb.", "Show that can never takes -s."],
      ["Match sentences and pictures (Activity 5).", "Complete the chart in pairs (Activity 6)."],
      ["Tell the class about yourself and a friend (Activity 7): I can swim, but my friend can't."],
      "Vote on the most surprising ability.", "Write six sentences about what you can and can't do."],
    [9, "Sugar or Sand", "Activities 5, 6 and 7", "Pronouns",
      "replace repeated nouns with the correct pronoun.",
      "A short repetitive text on the board, the Unit 9 story",
      ["Read: Amal has a bag. Amal's bag is red. Ask what sounds strange.", "Rewrite with pronouns and list them."],
      ["Circle the pronouns (Activity 5).", "Match and replace (Activities 6 and 7)."],
      ["Pairs rewrite a paragraph that repeats a name, using pronouns."],
      "Two pairs read aloud.", "Write about a friend using five pronouns."],
    [10, "Was It Yesterday?", "Activities 2, 4 and 5", "The simple past",
      "say what they did yesterday with regular and irregular past forms.",
      "A regular / irregular verb table",
      ["Tell a story: Yesterday I visited my grandmother. I went by bus.", "Sort the verbs into +ed and irregular."],
      ["Find the past forms in the role play (Activity 2).", "Complete the diary flow chart (Activity 4)."],
      ["Each pupil says one thing they did yesterday (Activity 5) and writes three more."],
      "Add new verbs to the class table.", "Write a six-sentence diary entry about last weekend."],
    [11, "Eco Friends", "Activities 1 and 2", "Free-time activities",
      "write a short paragraph about their free time with reasons.",
      "The Unit 11 role play, a paragraph frame",
      ["Read the role play and list what the friends like to do.", "Model: In my free time, I like to read because ..."],
      ["Build a word bank.", "Pairs talk about what they like and why."],
      ["Write a five- or six-sentence paragraph (Activity 2) using like to / enjoy and because."],
      "Swap: one thing done well, one to improve.", "Add a picture and bring it to display."]
  ]
};
