exports.g4 = {
  slug: "grade-4", label: "Grade 4", book: "Grade 4 English Pupil's Book",
  note: "These plans follow the Grade 4 Pupil's Book whose ten units run from My family and friends to Happy days; if your copy differs, match the plans to your own book. Grade 4 is still taught mainly through listening and speaking, with short reading and writing. Let pupils say everything before they write it. Stage times are for a 40-minute period.",
  plans: [
    [1, "My family and friends", "Lessons 1 and 2", "Greeting people and saying where you live",
      "greet a friend, answer How are you? and say their name and where they live.",
      "The Hello! song, name cards, a simple map or picture of the town",
      ["Greet pupils one by one: Hello, how are you? Answer for them: I'm fine, thank you.", "Teach the song from Lesson 1, then the answers I'm great / fine / good / okay."],
      ["Pupils practise the exchange in pairs (Practise with your friend).", "Model Lesson 2: I'm Sandani. I live in Matara. Pupils repeat with their own names."],
      ["Mingle: pupils greet five friends and ask What's your name? Where do you live?, then tell the class about one friend."],
      "Three pupils introduce a friend: This is Nisal. He lives in Galle.", "Write four sentences about yourself: name, age, grade, town."],
    [1, "My family and friends", "Lessons 4 and 5", "Talking about my family and parts of the body",
      "say how many people are in their family and name parts of the body.",
      "A family drawing on the board, body-part word cards",
      ["Draw your own family and say: There are four people in my family. This is my mother.", "Point to parts of the body and name them: head, neck, eyes, shoulder."],
      ["Groups of three introduce their families (Lesson 4).", "Listen and repeat the body-part words, then Simon says with them."],
      ["Pupils draw their family, label one person, and tell a partner: There are ... in my family. My brother has curly hair."],
      "Two pupils show their drawings to the class.", "Label a drawing of yourself with six body-part words."],
    [2, "Our beautiful garden", "Lessons 1 and 5", "There is and there are",
      "describe a garden using There is one ... and There are three ...",
      "The Unit 2 garden picture, real leaves or flowers",
      ["Show the garden picture: There is a tree. There are three birds.", "Write the rule: there is + one thing, there are + many things."],
      ["Listen, point and say the garden words: trees, birds, butterflies.", "Talk about Senuri's garden with the sentence frame (Lesson 1)."],
      ["Spot-the-difference in pairs (Lesson 5): each pupil says five sentences with there is / there are."],
      "Correct: There is three birds → There are three birds.", "Draw your home garden and write five sentences about it."],
    [2, "Our beautiful garden", "Lessons 2, 3 and 6", "Garden work: verbs, tools and following instructions",
      "name garden tools, say what people do in a garden, and follow a set of instructions.",
      "Pictures of a rake, ekel broom and watering can; paper and crayons",
      ["Mime watering and sweeping: I water the plants. She waters the plants.", "Show the tool pictures and name them (Lesson 3)."],
      ["Listen and repeat the action words: pick, water, sweep, plant.", "Match tools with the actions they are used for."],
      ["Listen and do (Lesson 6): pupils follow six instructions to draw and colour a garden picture, then check with a partner."],
      "Compare pictures: who followed every instruction?", "Write four things you can do in a garden."],
    [3, "Places around me", "Lessons 1 and 2", "Places in my village or town",
      "name places in their area and say what people do there.",
      "Picture cards: temple, church, post office, library, school, market",
      ["Hold up each card: This is a post office. We buy stamps here.", "Drill the place names with the class."],
      ["Look and say (Lessons 1 and 2) with the pictures in the book.", "Quick game: the teacher says what people do; pupils name the place."],
      ["Pupils draw a simple map of their village with four places and tell a partner about it."],
      "Two pupils name the places nearest their homes.", "Draw and label four places near your home."],
    [3, "Places around me", "Lesson 3", "Giving simple directions",
      "give and follow directions using go straight, turn right and turn left.",
      "The Lesson 3 map, arrow cards",
      ["Walk across the classroom saying: Go straight. Turn left. Stop.", "Show the arrow cards with the words."],
      ["Listen and trace the route on the map (Lesson 3)."],
      ["Pairs give directions from the school gate to a place on their own map; the partner traces it."],
      "One pair demonstrates for the class.", "Write three directions from your home to school."],
    [4, "Joy of work", "Lessons 1 and 2", "Occupations and workplaces",
      "name common occupations and say where each person works.",
      "Occupation picture cards, workplace cards",
      ["Show the cards: This is a doctor. A doctor works in a hospital.", "Build two columns on the board: person and place."],
      ["Listen, point and say the occupations (Lesson 1) and the workplaces (Lesson 2).", "Match each worker with a workplace."],
      ["Pupils tell the class about one worker they know: My uncle is a farmer. He works on a farm."],
      "Ask: what do you want to be?", "Draw a worker and write two sentences about the job."],
    [5, "Our festivals", "Lessons 1, 2 and 5", "Festivals, months and festive food",
      "name the festivals they celebrate, say which month each falls in, and name festive food.",
      "Festival pictures, a calendar, food pictures",
      ["Show the pictures: This is the Vesak festival. It is in May.", "Write the pattern: ... is in ... (month)."],
      ["Look and read (Lessons 1 and 2), then match festivals with months.", "Name the festive food: milk rice, watalappan (Lesson 5)."],
      ["Pupils tell a partner about their favourite festival: what they wear, eat and do."],
      "Two pupils tell the class.", "Draw your favourite festival and write four sentences."],
    [5, "Our festivals", "Lessons 4 and 7", "What are you doing? (present continuous)",
      "ask and answer What are you doing? using is / are + verb + ing.",
      "Action picture cards from the unit",
      ["Mime cooking and ask: What am I doing? Answer: You are cooking.", "Write the pattern is / am / are + verb + ing."],
      ["Act out the Lesson 4 dialogue in pairs.", "Match and speak (Lesson 7) using the pictures."],
      ["Mime chain: one pupil mimes a festival activity, the class asks What are you doing?, the pupil answers."],
      "Check spelling: making, cooking, singing.", "Write four sentences about what your family does at a festival."],
    [6, "Let's go shopping", "Lessons 2 and 3", "This, these, that, those and shopping talk",
      "use this / these and that / those and take part in a short shopping conversation.",
      "Classroom objects, price cards, a shop corner",
      ["Hold up one pen: This is a pen. Point far: That is a bag. Repeat with plurals.", "Model the shop talk: Can I help you? I want two mangoes."],
      ["Look and match (Lesson 2).", "Read the Lesson 3 dialogue in pairs."],
      ["Set up a class shop: pupils take turns as seller and buyer, using this / these / that / those and asking the price."],
      "One pair performs their shopping scene.", "Write a five-line shopping conversation."],
    [7, "My calendar", "Lessons 1 to 4", "Days, months and dates",
      "say the days of the week, the months of the year and today's date.",
      "A class calendar, day and month cards",
      ["Sing the days-of-the-week song (Lesson 1).", "Say the months in order, then show dates: Second - 2nd, third - 3rd."],
      ["Listen and repeat the days and months (Lessons 2 and 3).", "Read the dates aloud (Lesson 4) and find them on the class calendar."],
      ["Pupils make their own balloon calendar (Lesson 5) with the months and their birthday marked, then tell a friend: My birthday is on the 5th of June."],
      "Ask three pupils today's date.", "Write the date of your birthday and two family birthdays."],
    [7, "My calendar", "Lessons 6 and 7", "Weather and telling the time",
      "describe the weather and tell the time on the hour and half hour.",
      "Weather cards, a cardboard clock",
      ["Show the weather cards: It is sunny. It is rainy.", "Move the clock hands: It is eight o'clock. It is half past eight."],
      ["Listen and repeat the weather words (Lesson 6), then sing the weather song.", "Practise telling the time (Lesson 7)."],
      ["Pairs ask and answer: What's the weather like today? What time do you get up?"],
      "Set the clock and ask three pupils the time.", "Draw clocks for four things you do every day."],
    [8, "Playing games", "Lessons 1, 3 and 6", "Action words and saying what you like",
      "name action words, say what someone is doing now, and say which game they like.",
      "Open space, action word cards",
      ["Mime and say: walk, run, hop, skip (Lesson 1).", "Show the pattern: He is running. I like cricket."],
      ["Listen and mime the action words.", "Listen and repeat the is / am / are + verb + ing sentences (Lesson 3)."],
      ["Talk to five friends (Lesson 6): pupils ask What game do you like? and report: Amali likes netball."],
      "Count which game the class likes best.", "Write four sentences about the games you like."],
    [9, "Good practices", "Lessons 2, 3 and 4", "Polite words and good practices",
      "use Excuse me, May I ...? and thank you, and say what good practices they follow.",
      "The Unit 9 pictures, situation cards",
      ["Model politeness: Excuse me, may I come in? Thank you.", "Read two good practices from Lesson 3: Let's keep it clean."],
      ["Act out the Lesson 2 dialogue in pairs.", "Read and match the good practices with the pictures (Lesson 3)."],
      ["Groups take a situation card (in the bus, in the library, at the canteen) and act out the polite way to behave."],
      "The class names the polite words they heard.", "Write four good practices for your class."],
    [10, "Happy days", "Lessons 1 and 4", "Feelings and acting out a story",
      "say how they feel and act out a short dialogue with expression.",
      "Feeling cards: hungry, thirsty, tired, happy, sad",
      ["Mime being hungry and thirsty: I am hungry. I want to eat.", "Show the feeling cards and drill them."],
      ["Listen and match the feelings with the pictures (Lesson 1).", "Read the Lesson 4 dialogue aloud with the class."],
      ["Groups read and act out the dialogue (Lesson 4), showing the feelings in their voices and faces."],
      "Two groups perform; the class names the feelings shown.", "Draw a happy day and write four sentences about it."]
  ]
};
