exports.g7 = {
  slug: "grade-7", label: "Grade 7", book: "Grade 7 English Pupil's Book",
  note: "One plan for each of the ten units. Stage times are for a 40-minute period.",
  plans: [
    [1, "What You See", "Activities 3, 4 and 5", "Opposites and synonyms",
      "give the opposite of common adjectives and pick out words with similar meanings.",
      "Picture pairs (big / small, hot / cold), word cards",
      ["Show picture pairs and elicit the opposites.", "Explain synonyms with warm – hot and happy – glad."],
      ["Write opposites under the pictures (Activity 3) and match opposites (Activity 4).", "Circle the two synonyms in each set (Activity 5)."],
      ["Pairs describe a classmate's bag with three adjectives; the partner replies with the opposites or a synonym."],
      "Opposites race: teams of two, teacher calls a word.", "Write ten opposite pairs of your own."],
    [2, "Friends Indeed", "Activities 1, 2 and 3", "Reading a story and writing instructions",
      "answer questions on Fifi's story and write clear instructions in order.",
      "Fifi's story, instruction strips cut up for ordering",
      ["Pre-teach glass, spacious and freely, then read Fifi's story aloud.", "Show how instructions begin with a verb and use then, next."],
      ["Answer the Activity 1 questions in pairs.", "Put the cut-up instructions in order (Activity 2)."],
      ["Groups design a simple anti-dengue poster and write four instructions to go with it (Activity 3)."],
      "Groups show their posters.", "Write five instructions for looking after a pet."],
    [3, "Pleasure", "Activities 1, 5 and 7", "Was, were and will be",
      "use was / were for the past and will be for the future when telling a story.",
      "The Perahera dialogue, the Merryland story",
      ["Act out the Perahera dialogue with two pupils.", "Draw a timeline: yesterday – was / were, tomorrow – will be."],
      ["Fill in the Merryland story with was, were or will be (Activity 5).", "Listen and match letters to the playground passage (Activity 7)."],
      ["Pairs tell each other about a festival they saw and one they will see."],
      "Three pupils report their partner's answers.", "Write six sentences about a festival, past and future."],
    [4, "A Busy Day", "Activities 1, 3 and 9", "Reading a notice and possessive pronouns",
      "find information in a notice and use mine, yours, his, hers, ours and theirs.",
      "The scout notice, pupils' own pens and books",
      ["Act out Lahiru's busy day.", "Pick up a pupil's pen: Is this yours? Yes, it's mine. Build the list."],
      ["Complete the table from the notice (Activity 3).", "Fill in the possessive pronouns (Activity 9)."],
      ["Lost-property game: the teacher collects objects and pupils claim them using the pronouns."],
      "Correct: This book is her's → hers.", "Write a notice for a class event."],
    [5, "Once Upon a Time", "Activities 3, 4 and 8", "Joining sentences with and, but, or and when",
      "combine short sentences using and, but, or and when.",
      "Sentence strips about early people",
      ["Show two strips: Early people lived in caves. They hunted animals. Join them with and.", "Contrast and, but, or and when with examples."],
      ["Combine the sentences (Activity 3).", "Join sentences with when (Activity 8)."],
      ["Groups speak about the journey of human civilisation, each pupil giving one joined sentence (Activity 4)."],
      "Note the best joined sentences on the board.", "Write a short paragraph about a museum visit using when twice."],
    [6, "Better Safe Than Sorry", "Activities 1, 3 and 4", "Must, should, would and can",
      "give advice and rules with must and should and write a short note.",
      "The Suganya dialogue, a get-well card",
      ["Act out Suganya is Absent Today.", "Write rules and advice: You must wash your hands. You should rest."],
      ["Complete the sentences with must, should, would or can (Activity 3)."],
      ["Pupils write Suganya's thank-you note to her friends (Activity 4)."],
      "Read two notes aloud.", "Make a get-well card for someone you know."],
    [7, "Around the Country", "Activities 1, 6 and 8", "Adverbs and speaking about places",
      "use adverbs to describe how things happen and speak for one minute about a place.",
      "Ruvini's speech, A Trip to Jaffna, adverb cards",
      ["Read Ruvini's speech. Pupils answer the Activity 1 questions.", "Show adverbs: The train went slowly. They arrived safely."],
      ["Fill in the adverbs (Activity 6)."],
      ["Pupils choose a place and speak about it for a minute (Activity 8)."],
      "Class gives one compliment to each speaker.", "Write a description of a place you visited."],
    [8, "Wonders Around Us", "Activities 2, 3 and 6", "Reading for information and daily schedules",
      "take notes in a table from descriptions and talk about their daily schedule.",
      "Pictures of famous monuments, a blank table",
      ["Show the monuments and ask what pupils know.", "Model a schedule: 6.30 a.m. – I have breakfast."],
      ["Match descriptions and pictures (Activity 2) and complete the table (Activity 3)."],
      ["Pupils write their own schedule and compare it with a partner (Activity 6)."],
      "Pairs report one difference.", "Find one fact about a Sri Lankan monument."],
    [9, "Our Beautiful World", "Activities 4, 5 and 6", "Prepositions of movement",
      "use up, down, over, into, below and next to to describe a picture.",
      "The Unit 9 picture, a toy car or ball",
      ["Move a toy: It goes up the hill. It goes over the bridge.", "Write the prepositions with arrows."],
      ["Complete the sentences about the pictures (Activity 4)."],
      ["Describe the picture with the given words (Activity 5), then do the describe-and-draw task (Activity 6)."],
      "Compare drawings with the originals.", "Write five sentences about your way to school."],
    [10, "Future", "Activities 2, 3 and 7", "Predictions with will and won't",
      "make and discuss predictions about life in the future.",
      "The BBC predictions text",
      ["Read two predictions and ask Will this come true?", "Show will / won't + verb."],
      ["Make sentences with will / won't (Activity 7).", "Discuss the predictions (Activity 2)."],
      ["Groups write and present a prediction for one category (Activity 3)."],
      "Class votes on the most likely prediction.", "Write five predictions about your village in 2050."]
  ]
};

exports.g8 = {
  slug: "grade-8", label: "Grade 8", book: "Grade 8 English Pupil's Book",
  note: "The Grade 8 book numbers its activities by unit (1.1, 1.2 and so on). Stage times are for a 40-minute period.",
  plans: [
    [1, "Plan the Work, Work the Plan", "Activities 1.1, 1.2 and 1.3", "Reflexive pronouns",
      "use myself, yourself, himself and so on correctly in sentences.",
      "The English Day planning dialogue",
      ["Act out 1.1. Pick out We did it ourselves.", "List the reflexive pronouns beside the subject pronouns."],
      ["Answer the 1.2 questions.", "Rearrange the words into sentences (1.3)."],
      ["Pairs describe something they did by themselves last week."],
      "Correct hisself → himself.", "Write five sentences about things you do yourself."],
    [1, "Plan the Work, Work the Plan", "Activities 1.7 and 1.9", "Plural nouns and a friendly letter",
      "form regular and irregular plurals and plan a friendly letter.",
      "Amitha's letter",
      ["Write a cup, a boot, a knife, a child and elicit the plurals.", "Read Amitha's letter aloud; label its parts."],
      ["Write the plurals (1.7)."],
      ["Pupils write a short letter to a pen friend about a trip they are planning."],
      "Check the address and greeting layout.", "Finish the letter neatly."],
    [2, "Winged Friends", "Activities 2.5, 2.6 and 2.7", "Must, have to and should",
      "express rules, needs and advice with must, have to / has to and should.",
      "The substitution table in 2.5",
      ["Contrast: You must wear a seat belt (rule). You should rest (advice).", "Add have to / has to."],
      ["Build sentences from the table (2.5).", "Complete the blanks (2.6)."],
      ["Write three sentences each with the three forms and their negatives (2.7)."],
      "Pairs read and correct each other.", "Write rules for looking after birds."],
    [3, "Let's Be Considerate", "Activities 3.1 and 3.3", "Joining sentences with since and as",
      "join a reason and a result using since and as.",
      "The bus-stop role play",
      ["Act out 3.1.", "Show: Since it was raining, we stayed home."],
      ["Join the sentences (3.3)."],
      ["Pupils write three sentences about kind acts using since and as."],
      "Share the kindest act.", "Write a short paragraph on courtesy."],
    [3, "Let's Be Considerate", "Activities 3.5 and 3.8", "Reading a story aloud and tongue twisters",
      "read aloud clearly with good pace and pronunciation.",
      "The Magic Words story, tongue twisters",
      ["Model-read part of The Magic Words.", "Say the tongue twisters slowly, then faster."],
      ["Pairs read the story, taking turns by paragraph."],
      ["Groups perform the story as a short drama with the magic words."],
      "Tongue twister challenge.", "Practise one tongue twister at home."],
    [4, "Mother Nature", "Activities 4.5, 4.6 and 4.7", "Prepositions and instructions",
      "use prepositions in instructions and label a picture from a description.",
      "The picture for 4.7",
      ["Review prepositions with classroom objects.", "Read the 4.6 instructions aloud."],
      ["Put the instructions in the correct order (4.6)."],
      ["Listen and label the picture (4.7), then pairs describe their own picture."],
      "Check labels together.", "Write instructions for planting a tree."],
    [5, "Between the Miles", "Activities 5.2 and 5.6", "Word building and comparisons",
      "add -ly, -ful, -ness and -less to base words and use comparatives and superlatives.",
      "The word-building table",
      ["Show care → careful, careless, carefully.", "Compare three pupils' heights: taller, the tallest."],
      ["Complete the table (5.2) and the worksheet (5.6)."],
      ["Pupils describe one of the smallest things they know (5.5)."],
      "Share one comparison.", "Write six comparison sentences about your family."],
    [6, "When We Are Together", "Activities 6.5, 6.6 and 6.7", "The passive voice (present)",
      "recognise and form present simple passive sentences.",
      "The roti-making pictures",
      ["Show English is spoken all over the world. Ask who speaks it.", "Build be + past participle."],
      ["Match the roti pictures with the steps (6.5).", "Fill in the verb forms (6.6)."],
      ["Find the passive sentences in A Day in the Life of a News Reader (6.7) and describe how tea is made in the passive."],
      "Read two passive sentences aloud.", "Describe how a local food is made."],
    [7, "The World of Children", "Activities 7.3, 7.8 and 7.9", "Past passive and a letter",
      "rewrite past events in the passive and write a descriptive letter.",
      "Sigiriya information table",
      ["Show: Sigiriya was built by King Kashyapa.", "Review letter layout."],
      ["Rewrite the historical events in the passive (7.3)."],
      ["Order the Sigiriya information (7.8) and write Sahan's letter (7.9)."],
      "Peer-check the layout.", "Write about a place you visited."],
    [8, "It's a Small World", "Activities 8.4, 8.5 and 8.7", "Future passive and writing an article",
      "use will be + past participle and write a short news article.",
      "Newspaper cuttings",
      ["Show: The match will be played tomorrow.", "Point out the parts of a newspaper article."],
      ["Complete the sentences (8.4 and 8.5)."],
      ["Write a short article in steps (8.7) about a school event."],
      "Read two headlines aloud.", "Collect one English news headline."],
    [9, "On Top of the World", "Activities 9.2 to 9.5", "Adverbs of frequency",
      "use always, usually, often, sometimes, rarely and never.",
      "A frequency scale from 0% to 100%",
      ["Place the adverbs on the scale.", "I always brush my teeth. I never ..."],
      ["Fill in the conversation (9.2) and write sentences from the pictures (9.3)."],
      ["Group sentence chain (9.4), then write a paragraph (9.5)."],
      "Check adverb position.", "Write about your weekend habits."],
    [10, "Beyond the Classroom", "Activities 10.3 and 10.6", "The past perfect and telling stories",
      "use the past perfect to show which past action happened first.",
      "The English Day conversation, a timeline",
      ["Show: When I arrived, the bus had left.", "Draw two past points on a timeline."],
      ["Complete the past perfect blanks (10.3)."],
      ["Groups tell interesting stories and write one using inverted commas (10.6)."],
      "One group reads its story.", "Write a story ending with a surprise."]
  ]
};
