exports.g9 = {
  slug: "grade-9", label: "Grade 9", book: "Grade 9 English Pupil's Book",
  note: "One plan for each of the ten units. Stage times are for a 40-minute period.",
  plans: [
    [1, "Everybody Is Good at Something", "Activities 3, 4 and 7", "Collective nouns and subject–verb agreement",
      "choose is / are and has / have with collective nouns and write a paragraph about a friend.",
      "The TV programme dialogue",
      ["Act out Activity 1.", "Show: The team is ready. The crew has arrived."],
      ["Fill in the blanks (Activities 3 and 4)."],
      ["Write a paragraph about a best friend's talent for the wall newspaper (Activity 7)."],
      "Read two paragraphs aloud.", "Write about your own talent."],
    [2, "May I Help You?", "Activities 1, 5 and 8", "Shopping language and commas in lists",
      "use shopping expressions and punctuate lists correctly.",
      "A grocery list, price cards",
      ["Act out the supermarket dialogue.", "Show: We need rice, sugar and dhal. Point to the commas."],
      ["Insert commas (Activity 8) and read the sentences aloud, pausing at commas."],
      ["Groups prepare a grocery list and role-play shopping (Activity 5)."],
      "One group performs.", "Write a shopping list and a short dialogue."],
    [3, "Meeting", "Activities 3, 7 and 8", "Greetings and adjectives",
      "use greetings for different occasions and describe with adjectives.",
      "Greeting pictures",
      ["Show the pictures and elicit the greetings.", "Find the adjectives in Activity 6."],
      ["Write the greetings (Activity 3).", "Write sentences with the adjectives (Activity 7)."],
      ["Groups plan points for a speech on healthy food (Activity 8)."],
      "One group presents.", "Write the speech in full."],
    [4, "Extinct Friends", "Activities 3, 4 and 8", "Retelling a story",
      "retell a story in their own words and speak about an extinct animal.",
      "The Ice Age story, dinosaur pictures",
      ["Act out Nethula's Tour to the Ice Age.", "Model a retelling with first, then, finally."],
      ["Pupils relate the dream to a partner (Activity 3)."],
      ["Write the story in own words (Activity 4) and speak about an extinct creature (Activity 8)."],
      "Pairs swap and check sequence words.", "Find three facts about an extinct animal."],
    [5, "A Second Chance Called Tomorrow", "Activities 5, 10 and 12", "The passive and a congratulation letter",
      "transform active sentences into the passive and write a congratulatory letter.",
      "The 100 Metres extract",
      ["Read the extract and discuss Mudalihamy's victory.", "Show: Rahim wrote a letter → A letter was written by Rahim."],
      ["Transform sentences into the passive (Activity 12)."],
      ["Write a letter congratulating Mudalihamy (Activity 10)."],
      "Check the letter format.", "Write five passive sentences about your school."],
    [6, "Art", "Activities 2, 3 and 5", "Pronunciation and using a dictionary",
      "use dictionary entries to find meanings and word classes.",
      "Dictionaries, the dictionary page",
      ["Say the words in Activity 2 and find the shared sound.", "Explain a dictionary entry: headword, word class, meaning."],
      ["Answer the dictionary questions (Activity 3)."],
      ["Use the highlighted words in the text in new sentences (Activity 5)."],
      "Dictionary race.", "Find five new words and their meanings."],
    [7, "Where We Are", "Activities 3, 4 and 6", "Speaking on a topic and the passive",
      "give a short talk and change sentences into the passive, leaving out the doer when not needed.",
      "Pictures of dwellings",
      ["Show the dwellings and name them.", "Model a one-minute talk on Earth is Our Home."],
      ["Change sentences into the passive (Activity 6)."],
      ["Pupils give their own talk (Activity 3) and begin a picture dictionary of dwellings (Activity 4)."],
      "Peer feedback on eye contact and clarity.", "Complete the picture dictionary."],
    [8, "Success Through Creativity", "Activities 3, 5 and 8", "Relative pronouns and writing instructions",
      "join ideas with who, which, whose, where and when and write upcycling instructions.",
      "An empty bottle or tin",
      ["Read Upcycling – Turning Trash into Treasure.", "Show: This is the bottle which I turned into a vase."],
      ["Fill in the relative pronouns (Activity 3)."],
      ["Write instructions for upcycling an object (Activity 8)."],
      "Groups show their ideas.", "Make the upcycled object."],
    [9, "The Greatest Wealth", "Activities 5, 6 and 7", "Conditional sentences",
      "build first and second conditional sentences.",
      "The conditional table",
      ["Show: If we exercise, we will be healthy. If I had time, I would ...", "Contrast real and imagined situations."],
      ["Build sentences from the table (Activity 5) and match clauses (Activity 7)."],
      ["Complete the clauses with own ideas (Activity 6)."],
      "Share the most creative sentence.", "Write five sentences about good health."],
    [10, "Be Happy, Be Bright, Be You!", "Activities 1 to 3", "Reported speech",
      "report statements and questions.",
      "The subject-choice dialogue",
      ["Act out Activity 1.", "Show how Raju reported the conversation."],
      ["Write sentences in reported speech (Activity 3)."],
      ["Pairs interview each other about subject choices and report the answers."],
      "Check tense changes.", "Report a conversation from home."]
  ]
};

exports.g10 = {
  slug: "grade-10", label: "Grade 10", book: "Grade 10 English Pupil's Book",
  note: "One plan for each of the fourteen units. Stage times are for a 40-minute period. Link the writing tasks to the O/L paper formats as you go.",
  plans: [
    [1, "People", "Activities 2, 3 and 4", "Describing appearance",
      "describe a person's appearance using adjectives in the right order.",
      "Pictures of people",
      ["Describe a picture: She has long, black hair.", "Build a word bank by category."],
      ["Describe the pictures (Activity 2) and identify the people (Activity 3)."],
      ["Write a description of the class teacher and present it (Activity 4)."],
      "Class guesses who is being described.", "Describe a family member."],
    [2, "On Your Way", "Activities 1, 2 and 4", "Giving directions",
      "read a map and give directions.",
      "The map, a school plan",
      ["Model directions on the map: Go straight, turn left.", "List direction phrases."],
      ["Mark the way on the map (Activity 1) and identify places (Activity 2)."],
      ["Draw a school map and describe it (Activity 4)."],
      "Pairs test each other's directions.", "Write directions from school to your home."],
    [3, "Travel", "Activities 5 and 6", "Present continuous passive",
      "describe what is being done with is / are being + past participle.",
      "Pictures of the hotel crew at work",
      ["Show: The goods are being loaded.", "Build the form on the board."],
      ["Describe the pictures (Activity 5)."],
      ["Form passive sentences for the picture (Activity 6)."],
      "Peer-check the verb forms.", "Describe your school at 8 a.m."],
    [4, "Let's Talk", "Activities 1, 4 and 7", "Asking questions and interviewing",
      "form different question types and interview a partner.",
      "Find-someone-who sheet",
      ["Model the question types: yes/no, wh-, tag questions.", "Read the telephone conversation aloud."],
      ["Find someone who (Activity 1)."],
      ["Interview a friend about future plans (Activity 4)."],
      "Report findings.", "Write interview questions for a local hero."],
    [5, "Best Practices", "Activities 4 and 5", "Writing a formal letter",
      "plan and write a formal letter of complaint.",
      "The letter of complaint",
      ["Read the letter-writing instructions (Activity 4).", "Label the parts of the letter."],
      ["Analyse the model letter (Activity 5)."],
      ["Write a letter of complaint about a local problem."],
      "Peer-check with a checklist.", "Finish and correct the letter."],
    [6, "Information", "Activities 4, 5 and 6", "Writing a paragraph from a grid",
      "use information in a grid to write a paragraph about a book.",
      "The book grid",
      ["Read the newspapers paragraph.", "Show how the grid becomes sentences."],
      ["Write a paragraph from Hiruni's grid (Activity 5)."],
      ["Complete a grid about a book you read and write a paragraph (Activity 6)."],
      "Share one paragraph.", "Write about your favourite book."],
    [7, "Learning Is Fun", "Activities 2 and 3", "Describing a bar chart",
      "describe survey results from a bar chart.",
      "The bar chart",
      ["Model: Most students prefer ...", "List comparison phrases."],
      ["Describe the bar chart (Activity 2)."],
      ["Conduct a class survey and describe the result (Activity 3)."],
      "Present one result.", "Write a report on the class survey."],
    [8, "Healthy Food", "Activities 8 and 9", "Connectives of contrast",
      "join ideas with although, even though and in spite of.",
      "The finger millet passage",
      ["Show: Although it is cheap, it is nutritious.", "Contrast although and in spite of."],
      ["Fill in the blanks (Activity 8)."],
      ["Join sentence pairs (Activity 9) and write about homemade food."],
      "Correct in spite of it is.", "Write a paragraph on local food."],
    [9, "Nature", "Activities 2 and 7", "Reading a brochure and planning a poster",
      "extract information from a brochure and design a poster.",
      "The Kanneliya brochure",
      ["Read the brochure.", "Point out features of a good poster."],
      ["Fill in the grid (Activity 2)."],
      ["Plan a poster for a nature exhibition (Activity 7)."],
      "Display the posters.", "Complete the poster."],
    [10, "Personality", "Activities 2 and 7", "Ought to and need; interviewing",
      "use ought to and need and conduct a selection interview.",
      "The monitor-selection interview",
      ["Show: You ought to be punctual. You needn't worry.", "Read the interview."],
      ["Complete the sentences (Activity 2)."],
      ["Conduct an interview to select a class monitor (Activity 7)."],
      "Class votes on the best answers.", "Write about your best quality."],
    [11, "The Right Career", "Activities 5 and 6", "Job advertisements and applications",
      "read a job advertisement and write a letter of application.",
      "The newspaper advertisement",
      ["Read the advertisement.", "Show the structure of an application letter."],
      ["Discuss the job in pairs (Activity 5)."],
      ["Write a letter of application (Activity 6)."],
      "Check the letter format.", "Fill in a sample application form."],
    [12, "Success", "Activities 3 and 8", "Reported speech and completing an essay",
      "report statements and finish an essay using gathered points.",
      "Yoga's essay",
      ["Review reported speech.", "Read the essay opening."],
      ["Write sentences in reported speech (Activity 3)."],
      ["Complete Yoga's essay (Activity 8)."],
      "Share a strong ending.", "Write an essay on a successful person."],
    [13, "Future", "Activities 4, 5 and 7", "Conditionals and the future perfect",
      "use first and second conditionals and the future perfect.",
      "Timeline to 2030",
      ["Show: If I had a million rupees, I would ...", "Show: By 2030, I will have finished university."],
      ["Complete the conditional blanks (Activities 4 and 5)."],
      ["Use the future perfect (Activity 7) and describe life in 2030 (Activity 8)."],
      "Share one prediction.", "Write about your life in 2030."],
    [14, "Sports", "Activities 3, 5 and 6", "Past perfect continuous and a speech",
      "use the past perfect continuous and give a short speech on sport.",
      "Risuli's speech",
      ["Show: The boys had been playing in the mud.", "Read Risuli's speech."],
      ["Complete the sentences (Activity 3)."],
      ["Write and present a paragraph about a favourite sport (Activity 6)."],
      "Class feedback on delivery.", "Write about a sporting event."]
  ]
};

exports.g11 = {
  slug: "grade-11", label: "Grade 11", book: "Grade 11 English Pupil's Book",
  note: "One plan for each of the ten units. Stage times are for a 40-minute period. Grade 11 lessons also prepare pupils for the O/L paper, so keep the writing tasks close to the paper formats.",
  plans: [
    [1, "Our Responsibilities", "Activities 7, 8 and 10", "Modals for advice",
      "give advice about responsible citizenship using modals.",
      "The vandalism article",
      ["Read the article.", "Show: We should protect public property."],
      ["Write instructions (Activity 7) and sentences from the picture (Activity 8)."],
      ["Complete Farah's letter (Activity 10)."],
      "Share one piece of advice.", "Write a letter about a community problem."],
    [2, "Facing Challenges", "Activities 5, 7 and 8", "Organising an event and a speech",
      "plan a morning assembly and organise a speech with a mind map.",
      "The assembly discussion, a mind map",
      ["Act out the assembly discussion (Activity 5).", "Show Kamalesh's mind map."],
      ["Number the events from the announcements (Activity 7)."],
      ["Prepare a mind map and speech in groups (Activity 8)."],
      "One group delivers the speech.", "Write the speech in full."],
    [3, "Great Lanka", "Activities 6, 7 and 8", "Adjectives and a presentation on Sri Lanka",
      "use adjectives and past forms to present information about Sri Lanka.",
      "A map of Sri Lanka",
      ["Read the documentary conversation.", "Find the adjectives (Activity 6)."],
      ["Write past forms and sentences (Activity 8)."],
      ["Groups present on Sri Lanka (Activity 7)."],
      "Peer feedback.", "Write a description of a place in Sri Lanka."],
    [4, "For a Better Tomorrow", "Activities 4, 5 and 6", "Paragraph from a tree diagram and reported speech",
      "write a paragraph from a diagram and report an interview.",
      "The three R's tree diagram",
      ["Practise the TV interview (Activity 1).", "Show how the diagram becomes a paragraph."],
      ["Write about the three R's (Activity 4). Convert sentences to reported speech (Activity 6)."],
      ["Write and act an interview script (Activity 5)."],
      "One group performs.", "Report the interview in writing."],
    [5, "Best Use of Time", "Activities 3, 7 and 8", "Apologies and advertisements",
      "write an apology and understand a newspaper advertisement.",
      "The newspaper advertisement",
      ["Act out the Rajan and Samith dialogue.", "Show apology phrases."],
      ["List the advantages of working on time (Activity 3)."],
      ["Write an apology to the master-in-charge (Activity 7) and study the advertisement (Activity 8)."],
      "Read an apology aloud.", "Write a timetable for your study week."],
    [6, "A Moment of Fun", "Activities 3, 4 and 8", "Determiners and writing a notice",
      "use determiners and write a notice.",
      "The drama notice",
      ["Read the drama dialogue.", "Underline determiners (Activity 3)."],
      ["Complete sentences with determiners (Activity 4)."],
      ["Prepare a notice for an event (Activity 8)."],
      "Check the notice format.", "Write a notice for a school club."],
    [7, "A Simple Living", "Activities 1, 5 and 7", "Instructions and collective nouns",
      "write instructions and use collective nouns.",
      "Instruction pictures",
      ["Show the pictures and model instructions.", "Show: a bunch of grapes, a flock of birds."],
      ["Write instructions for the pictures (Activity 1). Form collective nouns (Activity 5)."],
      ["Complete the collective noun grid (Activities 6 and 7) and use them in a paragraph."],
      "Collective noun quiz.", "Write about a simple life."],
    [8, "Reading Is Fun", "Activities 3, 7 and 8", "Adjectives and a letter of inquiry",
      "use adjectives and write a formal letter of inquiry.",
      "The Robinson Crusoe extract",
      ["Read the extract.", "Adjective game (Activity 3)."],
      ["Discuss buying books for the Readers' Club (Activity 7)."],
      ["Write a letter to a bookshop manager (Activity 8)."],
      "Check the letter format.", "Finish the letter."],
    [9, "Enigma", "Activities 4, 5 and 7", "Writing from a data sheet and debating",
      "write a report from notes and take part in a debate.",
      "The data sheet",
      ["Read the telephone dialogue (Activity 1).", "Model turning notes into sentences."],
      ["Complete the data sheet (Activity 4) and write the incident (Activity 5)."],
      ["Hold a debate on a given topic (Activity 7)."],
      "Class decides the winning side.", "Write a description of a mystery."],
    [10, "Choices in Life", "Activities 3, 6 and 7", "Goal setting and an essay",
      "set personal goals and write an essay about ambitions.",
      "The goal-setting flow chart",
      ["Read Setting Your Personal Goals.", "Complete the flow chart (Activity 3)."],
      ["Talk to a partner about goals (Activity 6)."],
      ["Write an essay about goals and ambitions (Activity 7)."],
      "Share one goal.", "Finish the essay."]
  ]
};
