// Builds _src/pages/practical-english-ielts-essays-3.json from the essay data
// in this folder, and updates the list on the model essays hub page.
// Usage: node tools/ielts/gen-essays.js
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "../..");
const essays = [...require("./essays-a.js").essays, ...require("./essays-b.js").essays];
const BASE = "practical-english/ielts/model-essays";
const total = 10 + essays.length;

const crumbs = [
  { label: "Practical English", url: "practical-english/" },
  { label: "IELTS", url: "practical-english/ielts/" },
  { label: "Model essays", url: BASE + "/" }
];

const page = (e, i) => {
  const next = essays[i + 1];
  return {
    slug: `${BASE}/${e.slug}`,
    title: `Model Essay ${e.number}: ${e.title}`,
    metaTitle: `IELTS Task 2 Model Essay: ${e.title} | Band 9 sample answer | RCF English`,
    description: `A full IELTS Writing Task 2 model answer on ${e.topic.toLowerCase()}, with the plan behind it, the language worth borrowing and how it meets the four band criteria. Written by RCF English.`,
    keywords: `IELTS task 2 model essay, ${e.topic.toLowerCase()} IELTS essay, band 9 sample answer, ${e.type.split(":")[0].toLowerCase()} IELTS essay`,
    kicker: `Model essay ${e.number} of ${total}: ${e.type.split(":")[0].toLowerCase()}`,
    kind: "page",
    breadcrumbs: crumbs,
    backTo: { label: "Model essays", url: BASE + "/" },
    hero: { text: `${e.type}. The question, a plan, the essay itself, and why it would score well.` },
    blocks: [
      {
        type: "callout", style: "legal", title: "Unofficial original RCF practice material",
        text: ["Original question and essay written by RCF English. Not endorsed by the British Council, IDP: IELTS Australia or Cambridge University Press & Assessment."]
      },
      { type: "prose", heading: "The question", level: "h2", text: [...e.question, "*Give reasons for your answer and include any relevant examples from your own knowledge or experience.*", "*Write at least 250 words.*"] },
      { type: "table", heading: "The plan", level: "h2", stacked: true, columns: ["Paragraph", "Content"], rows: e.plan },
      {
        type: "model", heading: "The model essay", level: "h2",
        items: [{
          // Counted from the essay itself. A stated figure that disagrees
          // with the text is the first thing a careful student notices.
          label: `Original RCF model answer (${e.model.join(" ").trim().split(/\s+/).length} words)`,
          prompt: e.question.map((q) => q.replace(/\*/g, "")).join(" "),
          sample: e.model
        }]
      },
      { type: "terms", heading: "Language worth borrowing", level: "h2", items: e.terms.map(([term, def]) => ({ term, def })) },
      {
        type: "table", heading: "Why this would score well", level: "h2", stacked: true,
        intro: ["The four things an examiner marks, and what this essay does about each. The wording of the criteria is IELTS's own and is published for candidates; the comments are ours."],
        columns: ["Criterion", "What this essay does"], rows: e.criteria
      },
      { type: "checklist", heading: "Check your own attempt", level: "h2", items: e.checklist },
      {
        type: "callout", style: "tip", title: "Use it, do not memorise it",
        text: ["An essay learnt by heart is easy to spot and cannot fit the question you are actually given. Take the shapes from *Language worth borrowing*, write your own answer to this question in forty minutes, then compare."]
      },
      {
        type: "related", heading: "Next", level: "h2",
        items: [
          ...(next ? [{ title: `Essay ${next.number}: ${next.title}`, url: `${BASE}/${next.slug}/`, text: [next.type + "."] }] : []),
          { title: `All ${total} essays`, url: BASE + "/", text: ["The full list, with the question type of each."] }
        ]
      }
    ]
  };
};

const out = {
  _readme: [
    "IELTS TASK 2 MODEL ESSAYS 11 TO " + total,
    "Generated by tools/ielts/gen-essays.js from essays-a.js and essays-b.js.",
    "Do not edit this file by hand: edit the data files and run the script.",
    "",
    "Every question and every essay is written by RCF English. Nothing is",
    "taken from Cambridge IELTS or any other published test, and no page",
    "claims to answer one."
  ],
  pages: essays.map(page)
};
fs.writeFileSync(path.join(ROOT, "_src/pages/practical-english-ielts-essays-3.json"), JSON.stringify(out, null, 2) + "\n");

// The hub page lists every essay: extend its table and its wording.
const hubFile = path.join(ROOT, "_src/pages/practical-english-ielts-essays.json");
const hub = JSON.parse(fs.readFileSync(hubFile, "utf8"));
const hubPage = hub.pages.find((p) => p.slug === BASE);
const table = hubPage.blocks.find((b) => b.type === "table" && /essays$/i.test(b.heading || ""));
table.rows = table.rows.filter((r) => Number(String(r[0])) <= 10);
for (const e of essays) table.rows.push([String(e.number), e.topic, e.type, `[Read](${BASE}/${e.slug}/)`]);
table.heading = `The ${total} essays`;
hubPage.title = `${total} IELTS Task 2 Model Essays`;
hubPage.metaTitle = `${total} IELTS Task 2 Model Essays | Band 9 sample answers | RCF English`;
fs.writeFileSync(hubFile, JSON.stringify(hub, null, 2) + "\n");

console.log(`${essays.length} new essays written; hub now lists ${table.rows.length}`);
