// Builds _src/pages/practical-english-ielts-essays-3.json from the essay data
// in this folder, and updates the list on the model essays hub page.
// Usage: node tools/ielts/gen-essays.js
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "../..");
const essays = [...require("./essays-a.js").essays, ...require("./essays-b.js").essays];
const seo = require("./seo.js");
const BASE = "practical-english/ielts/model-essays";
const total = 10 + essays.length;

const crumbs = [
  { label: "Practical English", url: "practical-english/" },
  { label: "IELTS", url: "practical-english/ielts/" },
  { label: "Model essays", url: BASE + "/" }
];

const page = (e, i) => {
  const next = essays[i + 1];
  return {
    slug: `${BASE}/${e.slug}`,
    title: `Model Essay ${e.number}: ${e.title}`,
    // No band score in the title: no examiner has marked these essays.
    metaTitle: `IELTS Writing Task 2 Sample Answer: ${e.title} | RCF English`,
    description: `A full IELTS Writing Task 2 model answer on ${e.topic.toLowerCase()}, with the plan behind it, the language worth borrowing and how it meets the four band criteria. Written by RCF English.`,
    keywords: `IELTS writing task 2 sample answer, IELTS ${e.topic.toLowerCase()} essay, ${seo.typeTag(e.type).toLowerCase()} IELTS, IELTS model essay, IELTS essay example`,
    tags: seo.essayTags(e.slug, e.type),
    ...seo.ESSAY_SCHEMA,
    kicker: `Model essay ${e.number} of ${total}: ${e.type.split(":")[0].toLowerCase()}`,
    kind: "page",
    breadcrumbs: crumbs,
    backTo: { label: "Model essays", url: BASE + "/" },
    hero: { text: `${e.type}. The question, a plan, the essay itself, and why it would score well.` },
    blocks: [
      {
        type: "callout", style: "legal", title: "Unofficial original RCF practice material",
        text: ["Original question and essay written by RCF English. Not endorsed by the British Council, IDP: IELTS Australia or Cambridge University Press & Assessment."]
      },
      { type: "prose", heading: "The question", level: "h2", text: [...e.question, "*Give reasons for your answer and include any relevant examples from your own knowledge or experience.*", "*Write at least 250 words.*"] },
      { type: "table", heading: "The plan", level: "h2", stacked: true, columns: ["Paragraph", "Content"], rows: e.plan },
      {
        type: "model", heading: "The model essay", level: "h2",
        items: [{
          // Counted from the essay itself. A stated figure that disagrees
          // with the text is the first thing a careful student notices.
          label: `Original RCF model answer (${e.model.join(" ").trim().split(/\s+/).length} words)`,
          prompt: e.question.map((q) => q.replace(/\*/g, "")).join(" "),
          sample: e.model
        }]
      },
      { type: "terms", heading: "Language worth borrowing", level: "h2", items: e.terms.map(([term, def]) => ({ term, def })) },
      {
        type: "table", heading: "Why this would score well", level: "h2", stacked: true,
        intro: ["The four things an examiner marks, and what this essay does about each. The wording of the criteria is IELTS's own and is published for candidates; the comments are ours."],
        columns: ["Criterion", "What this essay does"], rows: e.criteria
      },
      { type: "checklist", heading: "Check your own attempt", level: "h2", items: e.checklist },
      {
        type: "callout", style: "tip", title: "Use it, do not memorise it",
        text: ["An essay learnt by heart is easy to spot and cannot fit the question you are actually given. Take the shapes from *Language worth borrowing*, write your own answer to this question in forty minutes, then compare."]
      },
      {
        type: "related", heading: "Next", level: "h2",
        items: [
          ...(next ? [{ title: `Essay ${next.number}: ${next.title}`, url: `${BASE}/${next.slug}/`, text: [next.type + "."] }] : []),
          { title: `All ${total} essays`, url: BASE + "/", text: ["The full list, with the question type of each."] }
        ]
      }
    ]
  };
};

const out = {
  _readme: [
    "IELTS TASK 2 MODEL ESSAYS 11 TO " + total,
    "Generated by tools/ielts/gen-essays.js from essays-a.js and essays-b.js.",
    "Do not edit this file by hand: edit the data files and run the script.",
    "",
    "Every question and every essay is written by RCF English. Nothing is",
    "taken from Cambridge IELTS or any other published test, and no page",
    "claims to answer one."
  ],
  pages: essays.map((e, i) => {
    const p = page(e, i);
    p.blocks = seo.withShare(p.blocks, seo.shareBlock(`IELTS Writing Task 2 sample answer: ${e.title}, with the plan, useful language and how it meets the four criteria.`, seo.HASHTAGS_TASK2));
    return p;
  })
};
fs.writeFileSync(path.join(ROOT, "_src/pages/practical-english-ielts-essays-3.json"), JSON.stringify(out, null, 2) + "\n");

// The hub page lists every essay: extend its table and its wording.
const hubFile = path.join(ROOT, "_src/pages/practical-english-ielts-essays.json");
const hub = JSON.parse(fs.readFileSync(hubFile, "utf8"));
const hubPage = hub.pages.find((p) => p.slug === BASE);
const table = hubPage.blocks.find((b) => b.type === "table" && /essays$/i.test(b.heading || ""));
table.rows = table.rows.filter((r) => Number(String(r[0])) <= 10);
for (const e of essays) table.rows.push([String(e.number), e.topic, e.type, `[Read](${BASE}/${e.slug}/)`]);
table.heading = `The ${total} essays`;
hubPage.title = `${total} IELTS Task 2 Model Essays`;
hubPage.metaTitle = `${total} IELTS Writing Task 2 Sample Answers, with plans and analysis | RCF English`;
hubPage.keywords = "IELTS writing task 2 sample answers, IELTS model essays, IELTS essay examples, IELTS writing task 2 samples with answers, IELTS essay structure";
hubPage.tags = ["IELTS Writing Task 2", "Sample answers", "Opinion essays", "Discussion essays", "Problem and solution", "Academic and General Training"];
hubPage.blocks = seo.withShare(hubPage.blocks, seo.shareBlock(`${total} IELTS Writing Task 2 sample answers, each with a plan, useful language and how it meets the four criteria.`, seo.HASHTAGS_TASK2));
fs.writeFileSync(hubFile, JSON.stringify(hub, null, 2) + "\n");

console.log(`${essays.length} new essays written; hub now lists ${table.rows.length}`);
